api/app.py
import settings
from flask import Flask
from views import router

app = Flask(__name__)
app.config["UPLOAD_FOLDER"] = settings.UPLOAD_FOLDER
app.secret_key = "secret key"
app.register_blueprint(router)

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=settings.API_DEBUG_FLAG)

api/views.py
import json
import os
import settings
import utils
from flask import (
    Blueprint,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from middleware import model_predict

router = Blueprint("app_router", __name__, template_folder="templates")

@router.route("/new_prediction", methods=["GET"])
def new_upload():
  # context = {
  #             'models' : settings.AVAILABLE_MODELS
  #           }
  #return render_template("index.html", context=context, scroll="upload_image")
  return render_template("index.html",  scroll="upload_image")




@router.route("/", methods=["GET", "POST"])
def index():
    """
    GET: Index endpoint, renders our HTML code.

    POST: Used in our frontend so we can upload and show an image.
    When it receives an image from the UI, it also calls our ML model to
    get and display the predictions.
    """
    
    if request.method == "GET":
        return render_template("index.html")

    if request.method == "POST":
        # No file received, show basic UI
        if "file" not in request.files:
            flash("No file part")
            return redirect(request.url)

        # File received but no filename is provided, show basic UI
        file = request.files["file"]
        if file.filename == "":
            flash("No image selected for uploading")
            return redirect(request.url)

        # File received and it's an image, we must show it and get predictions
        if file and utils.allowed_file(file.filename):
            
            # Creates unique name
            img_name = utils.get_file_hash(file)
            img_path = os.path.join(settings.UPLOAD_FOLDER,img_name)
            
            # Stores image in 'static\uploads'
            print('PATH:' , img_path)
            file.save(img_path)
            file.close()
            if 'rbtn_output_selection' in request.form:
              annotation_style = request.form['rbtn_output_selection']
            else:
              flash("** Please select an annotation style")
              return redirect(request.url+"#upload_image")

            if "heuristic" in request.form:
              show_heuristic = True
            else:
              show_heuristic = False
            
            print(request.form)
            print(img_name)
            print(annotation_style)

            # Sent image to be processed by the ML model
            mAP = model_predict(img_name, annotation_style, show_heuristic)
        
            # Updates context
            context = {
                    "mAP": mAP,
                    "filename": img_path,
                    "annotation_style": annotation_style,
                    "show_heuristic": show_heuristic
                    }
            
            # Update `render_template()` parameters as needed 
            return render_template("index.html", filename=img_name, context=context)
        # File received and but it isn't an image
        else:
            flash("Allowed image types are -> png, jpg, jpeg, gif")
            return redirect(request.url)


@router.route("/display/<filename>")
def display_image(filename):
    """
    Display image uploaded.
    """
    return redirect(url_for("static", filename="uploads/" + filename))

@router.route("/display_bbox/<filename>")
def display_bbox(filename):
    """
    Display image predicted by the model in our UI.
    """
    basename, extension = os.path.splitext(filename)
    filename2 = basename + "_bbox" + extension

    return redirect(url_for("static", filename="predictions/" + filename2))

@router.route("/display_heatmap/<filename>")
def display_heatmap(filename):
    """
    Display image predicted by the model in our UI.
    """
    basename, extension = os.path.splitext(filename)
    filename2 = basename + "_heat" + extension

    return redirect(url_for("static", filename="predictions/" + filename2))

@router.route("/display_heuristic/<filename>")
def display_heuristic(filename):
    """
    Display image predicted by the model in our UI.
    """
    basename, extension = os.path.splitext(filename)
    filename2 = basename + "_heur" + extension

    return redirect(url_for("static", filename="predictions/" + filename2))

@router.route("/predict", methods=["GET", "POST"])
def predict(file = None):
    """
    Endpoint used to get predictions without need to access the UI.

    Parameters
    ----------
    file : str
        Input image we want to get predictions from.

    Returns
    -------
    flask.Response
        JSON response from our API having the following format:
            {
                "success": bool,
                "prediction": str,
                "score": float,
            }

        - "success" will be True if the input file is valid and we get a
          prediction from our ML model.
        - "prediction" model predicted class as string.
        - "score" model confidence score for the predicted class as float.
    """
    
    response_data = {"success": False, "prediction": None, "score": None} 
    status_code = 400
     
    if request.method == "GET":  
        status_code = 405
        
    elif request.method == "POST":
        
        # Check for file received 
        if "file" in request.files: file = request.files['file']
        
        # File received and it's an image, we must show it and get predictions
        if file and utils.allowed_file(file.filename):
            
            # 1. Creates unique name
            img_name = utils.get_file_hash(file)
            img_path = os.path.join(settings.UPLOAD_FOLDER,img_name)
            # 2. Stores image in '\upload'
            file.save(img_path)
            
            # 3. Sents image to be processed by the ML model
            prediction, score = model_predict(img_name)
            
            # 4. Updates Response
            response_data  = {"success": True, "prediction": prediction, "score": score}
            status_code = 200
            
            # checks for BottleNeck response
            if prediction == 'BottleNeck': 
                response_data  = {"success": False, "prediction": prediction, "score": score}
                status_code = 400
            
        # File received but it isn't an image
        else:
            flash("Allowed image types are -> png, jpg, jpeg, gif") 
            # rpse = current_app.response_class( response = json.dumps(data), status = 400, mimetype = 'application/json')    # Instead of: rpse = {"Error": 'HTTP Bad Request', "status_code": 400, "prediction": None, "score": None}
        
    return current_app.response_class( response = json.dumps(response_data), status = status_code, mimetype = settings.RPSE_MIMETYPE) 
    


@router.route("/feedback", methods=["GET", "POST"])
def feedback():
    """
    Store feedback from users about wrong predictions on a plain text file.

    Parameters
    ----------
    report : request.form
        Feedback given by the user with the following JSON format:
            {
                "filename": str,
                "prediction": str,
                "score": float
            }

        - "filename" corresponds to the image used stored in the uploads
          folder.
        - "prediction" is the model predicted class as string reported as
          incorrect.
        - "score" model confidence score for the predicted class as float.
    """
    # Get report 
    if request.method == "GET": 
        report_str = request.form.get("report")
        
    elif request.method == "POST":
        
        report_str = request.form.get("report")
        if report_str:
            report_path = settings.FEEDBACK_FILEPATH
            with open(report_path, 'a') as f:
                f.write(report_str+'\n')

    return render_template("index.html")

api/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Frontend for Retail Store Object Detection."
    />
    <title>Retail Store Object Detection</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='web/styles/style.css') }}"
    />
  </head>

  <body>
    <header>
    </header>

    <hr style="margin-inline: -10px" />

    <section>
      <h1 id="title">Retail Store Object Detection</h1>

      {% if not filename %}

      <form method="post" action="/" enctype="multipart/form-data">
  
        <input type="file" id="uploaded_img" name="file" class="hidden" required>
        <div >Select an image to 
        <label for="uploaded_img" class="label_button"><u> Upload</u></label> </div>
        <br>

        <div id="form_detect">

          <div class="img_container">
            <img class="output_img" id="my_preview" />
          </div>
          
          <div class="form__group">
            <div>
              <input type="checkbox" id="heuristic" name="heuristic" value="True">
              <label for="heuristic"> Show heuristic detection</label><br>
            </div>
            <div>
              <div class="section__heading">Select annotation style &nbsp</div> 
              <div >
                <div class="div_checkbox">
                  <label><input type="radio", name="rbtn_output_selection" value="heatmap">Heatmap</label> <br>
                </div>
                <div class="div_checkbox">
                  <label><input type="radio", name="rbtn_output_selection" value="bbox">Bounding box</label> <br>
                </div>
              </div>
            </div>
            <div id="upload-section">
              <input id="upload-button" type="submit" value="Scan image" class="button" />
            </div>
          </div>
        </div>
      </form>
      
      {% endif %}

      {% if filename %}
        <div class="img_container">
              {% if context['annotation_style'] == "bbox" %}
              <img class="output_img"
                src="{{ url_for('app_router.display_bbox', filename=filename) }}"
              />
              {% endif %}
              {% if context['annotation_style'] == "heatmap" %}
              <img class="output_img"
                src="{{ url_for('app_router.display_heatmap', filename=filename) }}"
              />
              {% endif %}
              {% if context['show_heuristic'] %}
              <img class="output_img"
                src="{{ url_for('app_router.display_heuristic', filename=filename) }}"
              />
              {% endif %}

        </div>
        {% if context['mAP2'] %}
          <div class="row">
            <div class="col-25">
              <label for="subject">
                Mean Average Precision: {{ context['mAP'] }} </label
              ><br />
            </div>
          </div>
          <form id="form" method="POST" action="/feedback">
            <button type="submit">Report incorrect answer</button>
            <input
              name="report"
              style="visibility: hidden"
              value="{'filename': '{{ filename }}', 'mAP': '{{ context['prediction'] }}' }"
            />
          </form>
        {% endif %}

        <div><a href="{{ url_for('app_router.new_upload') }}" class="label_button">Upload</a> a new image</div>
    
      {% endif %}
    </section>

    

    <div id="messages-section">
      {% with messages = get_flashed_messages() %} {% if messages %} {% for
      message in messages %}

      <div>
        <p class="message">{{ message }}</p>
      </div>

      {% endfor %} {% endif %} {% endwith %}
    </div>

    <script src="{{ url_for('static', filename='web/js/app.js') }}"></script>

    <noscript>You need to enable JavaScript to view the full site.</noscript>
  </body>
</html>